package initcmd

// ConfigTemplate is the default config.toml content written by `ja2en init`.
//
// Defaults to Google AI Studio's gemini-2.5-flash-lite, the stable
// production-tier Flash-Lite model. Free tier requires no credit card.
// gemini-3.1-flash-lite-preview is faster on paper but returned frequent
// HTTP 503s under preview-tier load (April 2026); switch when it reaches GA.
const ConfigTemplate = `# ja2en config — generated by ja2en init
#
# Default provider: Google AI Studio (Gemini API) via OpenAI compat
#   - Get a free API key: https://aistudio.google.com/apikey
#   - export GEMINI_API_KEY="..." in your shell
#
# Profile precedence (highest to lowest):
#   --prompt-file <path>   ad-hoc prompt file (overrides profile prompt)
#   --model <slug>         ad-hoc model
#   --profile <name>       pick a named profile from this file
#
# Per-profile fields can override the top-level values:
#   model, api_base, api_key_env

default_profile = "simple"
model = "gemini-2.5-flash-lite"
api_base = "https://generativelanguage.googleapis.com/v1beta/openai"
api_key_env = "GEMINI_API_KEY"
timeout_seconds = 30

[profiles.simple]
prompt = """
You are a Japanese-to-English translator specializing in technical content for software engineers.
Translate the input Japanese text into natural English used by native engineers.
Output ONLY the translation. No explanations, no notes, no formatting, no quotes.
"""

# Optional: a backup profile that uses OpenRouter (e.g., for fallback or
# different models). Uncomment and set OPENROUTER_API_KEY in your shell.
#
# [profiles.openrouter]
# api_base = "https://openrouter.ai/api/v1"
# api_key_env = "OPENROUTER_API_KEY"
# model = "anthropic/claude-haiku-4.5"
# prompt = """
# You are a Japanese-to-English translator. Output ONLY the translation.
# """

# Optional: a custom detailed profile. Create the prompt file first.
#
# [profiles.detailed]
# prompt_file = "~/.config/ja2en/prompts/detailed.md"
# model = "gemini-2.5-flash-lite"
`
