package initcmd

// ConfigTemplate is the default config.toml content written by `ja2en init`.
//
// Defaults to OpenAI gpt-5.4-nano as of v0.3 — the small reasoning model with
// the strongest ja→en quality at this price point (Reddit / Intento / llmversus
// agree GPT edges Gemini on Asian-language pairs). Free tier is gone, but
// $5 prepaid covers ~3 years at typical CLI volume (1day/50 translations).
//
// reasoning_effort = "none" disables CoT entirely on gpt-5.4-nano. Translation
// is a non-reasoning task, so spending tokens on thinking only adds latency
// and cost. Note: gpt-5.4-nano supports "none" / "low" / "medium" / "high" /
// "xhigh" — "minimal" is NOT supported on this model (returns 400).
//
// Gemini 2.5 Flash-Lite is kept as a fallback profile, and DeepL Free as a
// 500K-chars/month emergency tier.
const ConfigTemplate = `# ja2en config — generated by ja2en init
#
# Default provider: OpenAI gpt-5.4-nano (paid)
#   - Sign up: https://platform.openai.com/
#   - Minimum prepaid: $5 (credits expire after 1 year)
#   - export OPENAI_API_KEY="sk-..." in your shell
#   - reasoning_effort = "none" disables chain-of-thought entirely,
#     keeping latency low for short translation calls. Supported values:
#     "none" / "low" / "medium" / "high" / "xhigh".
#
# Profile precedence (highest to lowest):
#   --prompt-file <path>   ad-hoc prompt file (overrides profile prompt)
#   --model <slug>         ad-hoc model
#   --profile <name>       pick a named profile from this file
#
# Per-profile fields can override the top-level values:
#   provider, model, api_base, api_key_env, reasoning_effort

default_profile = "openai"
timeout_seconds = 30

# OpenAI gpt-5.4-nano — strongest small ja→en at this price point.
[profiles.openai]
provider = "openai"
api_base = "https://api.openai.com/v1"
api_key_env = "OPENAI_API_KEY"
model = "gpt-5.4-nano"
reasoning_effort = "none"
prompt = """
You are a Japanese-to-English translator for software engineers.
Output ONLY the translation in natural, conversational English a native
engineer would actually write.

Style rules:
- Drop hedge words and fillers entirely. They become NOTHING in English:
  ってか / なんですけど / 〜だけど / 〜のかな / 〜って感じ / まあ / なんか.
  NEVER translate them as "well", "also", "by the way", "I wonder if".
- Drop polite request markers from casual contexts:
  〜してください / 〜してくださいね / 教えてください / 教えて.
  These become a plain question or imperative in English, NOT "Please ___."
- Keep politeness ONLY when the source uses formal request keigo:
  〜していただけませんか / 〜お願いいたします / お手数ですが / 恐れ入りますが /
  ご確認のほど.
- Match the register: casual Japanese -> casual English; formal Japanese ->
  formal English. Never over-elevate.
- Drop sentence-final particles ですか / ますか / ですね / でしょうか when the
  context is conversational; use plain English statements/questions.
- Prefer concise direct phrasing over verbose academic style.
- No explanations, no notes, no markdown formatting, no surrounding quotes.

Examples:

Input: ってかこれ見てほしいんだけど
Output: Look at this.

Input: WezTermで背景の色を変更したいんですけど、どうやればいいですか？教えてください
Output: How do I change the background color in WezTerm?

Input: 効いてないのかな？
Output: Is this not working?

Input: 明日出社する
Output: I'll come to the office tomorrow.

Input: ご確認のほどよろしくお願いいたします
Output: Please confirm at your earliest convenience.
"""

# Gemini fallback (Google AI Studio, OpenAI-compatible endpoint).
# Switch with: ja2en --profile gemini "テキスト"
# Free tier suffers from a 250K-TPM project-wide cap that thinking mode quickly
# exhausts; reasoning_effort = "none" disables thinking entirely on Gemini 2.5
# and keeps the practical RPD usable.
# Get a free API key: https://aistudio.google.com/apikey
[profiles.gemini]
provider = "openai"
api_base = "https://generativelanguage.googleapis.com/v1beta/openai"
api_key_env = "GEMINI_API_KEY"
model = "gemini-2.5-flash-lite"
reasoning_effort = "none"
prompt = """
You are a Japanese-to-English translator for software engineers.
Output ONLY the translation in natural, conversational English a native
engineer would actually write.

Style rules:
- Drop hedge words and fillers entirely. They become NOTHING in English:
  ってか / なんですけど / 〜だけど / 〜のかな / 〜って感じ / まあ / なんか.
  NEVER translate them as "well", "also", "by the way", "I wonder if".
- Drop polite request markers from casual contexts:
  〜してください / 〜してくださいね / 教えてください / 教えて.
  These become a plain question or imperative in English, NOT "Please ___."
- Keep politeness ONLY when the source uses formal request keigo:
  〜していただけませんか / 〜お願いいたします / お手数ですが / 恐れ入りますが /
  ご確認のほど.
- Match the register: casual Japanese -> casual English; formal Japanese ->
  formal English. Never over-elevate.
- Drop sentence-final particles ですか / ますか / ですね / でしょうか when the
  context is conversational; use plain English statements/questions.
- Prefer concise direct phrasing over verbose academic style.
- No explanations, no notes, no markdown formatting, no surrounding quotes.

Examples:

Input: ってかこれ見てほしいんだけど
Output: Look at this.

Input: WezTermで背景の色を変更したいんですけど、どうやればいいですか？教えてください
Output: How do I change the background color in WezTerm?

Input: 効いてないのかな？
Output: Is this not working?

Input: 明日出社する
Output: I'll come to the office tomorrow.

Input: ご確認のほどよろしくお願いいたします
Output: Please confirm at your earliest convenience.
"""

# DeepL emergency fallback — 500,000 characters/month free, no daily cap.
# Translation-only NMT API; ignores 'prompt' and 'model'. Endpoint is
# auto-detected from the API key suffix (":fx" -> api-free.deepl.com).
# Note: free-tier inputs may be used by DeepL for model training; avoid
# sending confidential text on this profile.
[profiles.deepl]
provider = "deepl"
api_key_env = "DEEPL_API_KEY"

# Optional: OpenRouter profile for alternative routing or model exploration.
# Uncomment and set OPENROUTER_API_KEY in your shell.
#
# [profiles.openrouter]
# provider = "openai"
# api_base = "https://openrouter.ai/api/v1"
# api_key_env = "OPENROUTER_API_KEY"
# model = "anthropic/claude-haiku-4.5"
# prompt = """
# You are a Japanese-to-English translator. Output ONLY the translation.
# """

# Optional: a custom detailed profile. Create the prompt file first.
#
# [profiles.detailed]
# provider = "openai"
# api_base = "https://api.openai.com/v1"
# api_key_env = "OPENAI_API_KEY"
# model = "gpt-5.4-nano"
# reasoning_effort = "low"
# prompt_file = "~/.config/ja2en/prompts/detailed.md"
`
